### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by tritemio** [bgamari/photon-tools#4]
Hi,

I just found your project and it looks great! I have a similar python project called FRETBursts that focuses more on smFRET burst analysis:

http://tritemio.github.io/FRETBursts/

But I think there is room for sharing code for low level routines for basic timestamps manipulation.

Looking forward hearing from you.
Antonio

**Comment by bgamari** [comment]
Hi @tritemio!

Good to hear from you. Your project looks like a great tool. Very well done!

At this point I am finishing my PhD and will be moving on to other pastures. Consequently the amount of development effort that I expend on `photon-tools` is now quite small (although there are still users in my lab).

The quality of the code itself is okay, but research code nevertheless. That being said, if you find some pieces that you'd like to use in your own project, feel free to do so (respecting the license, of course). The `photon_tools.io` modules support a number of useful formats (albeit with the need for helper executables; I had wanted to bind these properly but never quite got around to it). Moreover, if you find something that doesn't look quite right to you, let me know with an issue or pull request.

Good luck with your research.

Cheers!
- Ben

**Comment by tritemio** [comment]
Thanks for the nice words and good luck with your PhD!
