### ISSUE TITLE
favia error

### ISSUE THREAD

**Issue by imanyakin** [bgamari/photon-tools#6]
Hi Ben, 

Having Favia throw an error when running the 'fcs-corr' utility, any ideas about the cause?

`Traceback (most recent call last):
  File "/usr/local/bin/fcs-corr", line 240, in <module>
    anomaly_thresh=args.anomaly_thresh, **kwargs)
  File "build/bdist.linux-x86_64/egg/photon_tools/correlate/__init__.py", line 111, in corr_chunks
  File "build/bdist.linux-x86_64/egg/photon_tools/correlate/__init__.py", line 39, in corr
  File "build/bdist.linux-x86_64/egg/photon_tools/correlate/favia.py", line 90, in corr
photon_tools.correlate.favia.FaviaError: Favia threw an error: exit code 1

Cannot handle val -1431514704 for option '/tmp/tmpp9y2oZ'
Cannot handle val -1431514368 for option 'SH�������H�߾'
Cannot handle val -1431514720 for option 'SH��H�� H�dH�%('
Cannot handle val -1431514704 for option '/tmp/tmpYqCllz'
Cannot handle val -1431514368 for option 'SH�������H�߾'
Cannot handle val -1431514720 for option 'SH��H�� H�dH�%('
Cannot handle val -1431514704 for option '7.812500e-09'
Cannot handle val -1431514368 for option 'SH�������H�߾'
Cannot handle val -1431514720 for option 'SH��H�� H�dH�%('
Cannot handle val -1431514704 for option '1.000000e+00'
Cannot handle val -1431514368 for option 'SH�������H�߾'
Cannot handle val -1431514720 for option 'SH��H�� H�dH�%('
Cannot handle val -1431514704 for option '0.000000e+00'
Cannot handle val -1431514368 for option 'SH�������H�߾'
Cannot handle val -1431514720 for option 'SH��H�� H�dH�%('
Cannot handle val -1431514704 for option '8'
Cannot handle val -1431514368 for option 'SH�������H�߾'
Cannot handle val -1431514720 for option 'SH��H�� H�dH�%('
verbose: 0
xfn: /tmp/tmpp9y2oZ
yfn: /tmp/tmpYqCllz
jiffy: 7.8125e-09 s
fineness: 8 grains per octave == 26.5754 grains per decade
max_events: 0
short_grain: 0 s --> 0 bins == 0 s
Ooops: grain size less than bin size.`

**Comment by bgamari** [comment]
I'm afraid I'm going to need a bit more information to debug this. "Cannot handle val -1431514704 for option '/tmp/tmpp9y2oZ'" look quite bizarre.

**Comment by imanyakin** [comment]
This was a bit strange, reinstalling seems to have helped
